### ISSUE TITLE
Read Shopcarts

### ISSUE THREAD

**Issue by Adora2401** [2022-Spring-NYU-DevOps-Shopcarts/shopcarts#10]
**As a** User
 **I need** a service to read all the items in my shopcart
 **So that** I can keep track of what item I have put into my shopcart
   
 ### Details and Assumptions
 * GET method will be used
 * Use to view user's own shopcart
 * Expecting a list of the items and status code 200

 ### Acceptance Criteria  
   
 ```gherkin
 Given our local service is running and there is a shopcart with some items OR with no items
 When we execute GET on the relevant shopcart
 Then we get the list of items in the shopcart, respectively and status code 200
 ```

**Comment by TimothyXu** [comment]
Thanks for the work! Please create another pull request (but not approve it) for your branch after merging the new changes from main into your branch. I (or anyone else that sees it first) can approve your pull request!
