### ISSUE TITLE
Refactor APIs for Shopcarts (not include subroutines)

### ISSUE THREAD

**Issue by kdokm** [2022-Spring-NYU-DevOps-Shopcarts/shopcarts#113]
**As a** developer
 **I need** to refactor the code using a more advanced framework
 **So that** I can have generated documentation automatically
   
 ### Details and Assumptions
 * Using Flask-RESTX and Swagger
 * Add Swagger annotations
 * Add Swagger data models to document our API payloads
 * Refactor the /shopcarts and /shopcarts/{user_id} routes
 * Make sure all of the proper error codes returned (~e.g. 400 for an invalid user_id or item_id meaning not a non-negative integer, NOT 404~)  [EDIT: prof said default 404 for those is the right thing to do so switch back to /shopcarts/\<int:user_id\>] :(
 * After refactoring use ```flask routes``` to list all routes, make sure there are no static gets or other routes not specified by our API explicitly.

 ### Acceptance Criteria  
   
 ```gherkin
 Given we have refactored the above routes
 When we run nosetests and behave on the tests we had previously written on these routes
 Then all tests pass
 When we call a method on a route that produces an HTTP error
 Then we get JSON error messages back not HTML
 And we never get 500 error messages
 Given we have automatically generated the documentations using Swagger
 When we go to the URL /apidocs/
 Then we have comprehensive documentation of all of the routes available in our service as well as how to use them
 ```

**Comment by TimothyXu** [comment]
sorry i just realised we still need to add the swagger tags for automatically generating docs! since you've already done a lot of work, feel free to write a separate story for the swagger tags.

**Comment by kdokm** [comment]
I think most tags are already done? You can see docs in .../apidocs @TimothyXu

**Comment by TimothyXu** [comment]
@kdokm Yes you're right sorry! It's all done

**Comment by TimothyXu** [comment]
Copying my comment in the other PR: Most of the work is done which is great! Refactoring is fine. But: (we can open a different story to fix this if you wish so someone else can do it)

1. As prof said in our slack channel, A 400_BAD_REQUEST is reserved for the payload. Not the path. so we need to change all the urls back to int:shopcart_id etc. and not check for them manually. And when we try to call e.g. /shopcarts/wrongid we should get the default 404 from Flask and that's fine.
