### ISSUE TITLE
1 line of strange output after running nosetests

### ISSUE THREAD

**Issue by TimothyXu** [2022-Spring-NYU-DevOps-Shopcarts/shopcarts#117]
Currently in the nosetests output there is one line that's from std_out and I cannot figure out why only this one is special: '- Attempts to create an item with a non-positive int quantity
409 Conflict: Shopcart with user_id '21' already contains item with id '0'. Do you mean Update?'

Why is this in the nosetests output?

**Comment by kdokm** [comment]
I think it is not for non-positive but for 'Attempts creating an item with a duplicate ID' below, but I didn't check why the message is there. I can check it when I have time.

**Comment by TimothyXu** [comment]
I agree. Just don't know why this error message is special and escaped capture by nosetests.

**Comment by TimothyXu** [comment]
Solved by @kdokm
