### ISSUE TITLE
Create the initial microservice skeleton

### ISSUE THREAD

**Issue by Adora2401** [2022-Spring-NYU-DevOps-Shopcarts/shopcarts#12]
**As a** Developer
 **I need** to create initial microservice skeleton to loose coupling/binding RESTful APIs
 **So that** the whole team can work on the same skeleton and avoid teething problems
   
 ### Details and Assumptions
 * Using Flask
 * Using starter code from Professor's repos
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given we have pulled from the committed skeleton code repo
 When we start developing on our individual features
 Then there will not be a horrendous amount of conflicts when we all push, since we will have the same skeleton
 ```

**Comment by TimothyXu** [comment]
I reassigned this from me to yjjw per Professor's comments, since yjjw's starter code satisfied this already!
