### ISSUE TITLE
UI not showing some error messages

### ISSUE THREAD

**Issue by TimothyXu** [2022-Spring-NYU-DevOps-Shopcarts/shopcarts#138]
See https://nyudevopsspring2022-3.slack.com/archives/C033J6GUC6L/p1651569268516559

E.g. affects Get Item button, Remove button, Hold for Later button, Resume for Purchase button, and probably others too.

**Comment by TimothyXu** [comment]
Still not working after the PR per professor's suggestions; waiting for further advice

**Comment by yjjw** [comment]
> 

May I know which part "still not working" ? I think the current version will ensure that the inputs typed in the item_id, user_id, price and quantity fields must be numbers, not string texts

**Comment by TimothyXu** [comment]
> May I know which part "still not working" ? I think the current version will ensure that the inputs typed in the item_id, user_id, price and quantity fields must be numbers, not string texts

Oh interesting. I tried on Chrome and what you said is true and this should be fine. But on Safari both locally and at http://nyu-shopcart-service-sp2203-dev.us-south.cf.appdomain.cloud, we can still enter string texts
