### ISSUE TITLE
Set up Github

### ISSUE THREAD

**Issue by Adora2401** [2022-Spring-NYU-DevOps-Shopcarts/shopcarts#15]
**As a** developer
 **I need** everyone in team has the same development environment and keep track of development process
 **So that** we can pull/push the code to build the same environment and keep synchronized
   
 ### Details and Assumptions
 * Set up the repo and add everyone to the team
 *  Write instructions about the synchronization
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given the github repo is set
 When the developer uses push/pull
 Then the local repository and the remote repository gets synchronised according to the command
 ```

**Comment by TimothyXu** [comment]
Closing per answer from the Professor on Slack, this is an individual task and should not be on our Kanban board.
