### ISSUE TITLE
Flesh out root URL response and docstrings

### ISSUE THREAD

**Issue by TimothyXu** [2022-Spring-NYU-DevOps-Shopcarts/shopcarts#22]
**As a** System Administrator
 **I need** to understand what functionalities our API offers by reading the code
 **So that** I can use it to perform business operations.
   
 ### Details and Assumptions
 * We need to use comments and docstrings in our code especially routes.py to explain our API, and flesh out the root URL response (in routes.py) when all API calls have been implemented.
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given the Flask server is running
 When we go to the root URL of our service in a browser
 Then we see instructions detailing all API calls available as well as other pertinent information about our service
 ```

**Comment by kdokm** [comment]
Does this story refer to writing comments for the code or getting api lists from root URL or both? If it contains writing comments, I believe that it is what everyone should do when we are writing our code for each story.

**Comment by TimothyXu** [comment]
I was think both, but only for the doctoring at the top of routes.py. Because there are 2 things in that module that can only be done after all of the functionalities have been decided/implemented: 1. Doctoring at beginning of file outlining this module and what API calls we have, 2. the root URL response at /shopcarts displaying info about our micro service. This is my understanding, let me know if people agree!
