### ISSUE TITLE
Problem when starting the server

### ISSUE THREAD

**Issue by lemadmax** [2022-Spring-NYU-DevOps-Shopcarts/shopcarts#26]
![image.png](https://images.zenhubusercontent.com/620778d6fa23f12034c8ca07/96c2fdca-cc67-42ca-a1bc-f82257736ae7)

If we start our server using the line above, the nosetests won't work correctly. nosetests will stack and wait until we hit ctrl+c to terminate the server process.

Is there another way to start our server?

**Comment by yjjw** [comment]
Could you try "flask run" command in a bash terminal?

**Comment by TimothyXu** [comment]
This is the command I used that I think works: ```flask run -h 0.0.0.0 -p 8000```

**Comment by kdokm** [comment]
`flask run` should mostly works well. I think it actually uses the default host ip (which you can specify in `-h`) and default port (which you can specify in `-p`) to run the application.
If unfortunately, it does not work, it is probably that the default port is already used by another application. In this case, you can try `flask run -h 0.0.0.0 -p xxxx`, where `xxxx` can be any number.

**Comment by TimothyXu** [comment]
@lemadmax did any of these work?
