### ISSUE TITLE
Create Database Model and Schema

### ISSUE THREAD

**Issue by TimothyXu** [2022-Spring-NYU-DevOps-Shopcarts/shopcarts#3]
**As a** System Administrator
**I need** to create an appropriate database model and schema for the shopcarts/items business domain
**So that** I can store items in shopcarts as desired by customers. 
   
 ### Details and Assumptions
 * Each shopcart is uniquely associated to a user, by something like a userID
 * Each shopcart can contain multiple items, each of which can exist in multiple quantities
 * Each item has an associated price and a unique identifier of some kind (perhaps just name of item)
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given a userID
 When we trace through the schema
 Then we find an associated unique shop cart
 ```

**Comment by yjjw** [comment]
In addition to quantities of each item, shall we also add the associated price to each item?

**Comment by yjjw** [comment]
A question, can a user have more than one Shopcart?

**Comment by yjjw** [comment]
> A question, can a user have more than one Shopcart?

Never mind, I think I found the answer. We discussed last time and agreed that each user can only have a single shopcart
