### ISSUE TITLE
Need to be able to List Shopcarts

### ISSUE THREAD

**Issue by TimothyXu** [2022-Spring-NYU-DevOps-Shopcarts/shopcarts#4]
**As a** System Administrator
 **I need** to be able to use a REST API to list all shopcarts that exist at any given moment
 **So that** I can have access to every shopcart.
   
 ### Details and Assumptions
 * Use a REST API: GET .../shopcarts probably
 * Return should be an array of ids, identifying those shopcarts, in JSON form
 * Appending those ids to the URL should allow us access to those shopcarts via the REST API
 * Expect return a list of the shopcarts and status code 200

 ### Acceptance Criteria  
   
 ```gherkin
 Given our service is running and there are some or 0 shopcarts
 When we call LIST
 Then we get returns a list of the existing shopcarts and status code 200
 ```

**Comment by TimothyXu** [comment]
If I had understood REST API in the last lecture, the correct API call for this should be GET on [our-service]/shopcarts  . Do we agree?

**Comment by TimothyXu** [comment]
For bookkeeping purposes: at Backlog Refinement meeting on 22 Feb we agreed it should indeed be GET

**Comment by TimothyXu** [comment]
The current implementation for this story lists all 'shopcarts' as defined in our database schema, which includes all items. Is this the functionality we want? Or do we want our list_shopcarts method to return a list of all shopping carts with unique user_ids, as in the normal English meaning of shopcarts?

**Comment by kdokm** [comment]
Oh, it is because I assume .all() returns all shopcarts not including items. Sorry that I didn’t check it. So, I think maybe we should change .all() in model.py to fix it?

**Comment by TimothyXu** [comment]
I agree with this.
