### ISSUE TITLE
Change the way to create a new item in a shopping cart

### ISSUE THREAD

**Issue by TimothyXu** [2022-Spring-NYU-DevOps-Shopcarts/shopcarts#47]
**As a** system administrator
 **I need** to have a nested API 
 **So that** our service can be used intuitively as a RESTful service
   
 ### Details and Assumptions
 * Per the professor, use POST    /shopcarts/{customer_id}/items, giving the {item_id, item_name, price, quantity}
 * There is no need for the -1 dummy item for the empty shopcarts.
 * 
 ### Acceptance Criteria  
   
 ```gherkin
 Given {customer_id} is a valid customer_id
 And {item_id, item_name, price, quantity} is valid
 And shopcart with id {customer_id} does not have item with id {item_id}
 When we call POST on /shopcarts/{customer_id}/items passing in {item_id, item_name, price, quantity}
 Then service returns code 201 CREATED
 ```

**Comment by TimothyXu** [comment]
Updated ```name``` to ```item_name``` to conform to our current schema

**Comment by kdokm** [comment]
The tests may be affected by the change of common functions due to -1 issue. I will finish it later tonight so that you can get the latest version.

**Comment by TimothyXu** [comment]
no hurry. currently no problems.
