### ISSUE TITLE
Set up Development Environment

### ISSUE THREAD

**Issue by lemadmax** [2022-Spring-NYU-DevOps-Shopcarts/shopcarts#5]
**As a** Developer
 **I need** to have a consistent and repeatable development environment identical to all other team members
 **So that** I can benefit from Infrastructure as Code and not have inconsistent dev environments between different members
   
 ### Details and Assumptions
 * Set up docker files in a .devcontainer folder
 * Use the Visual Studio Code Remote Containers extension for docker integration

 ### Acceptance Criteria  
   
 ```gherkin
 Given we have cloned the remote repo containing our project
 When we execute "code ." on the project path
 Then Visual Studio Code opens to our project workspace and reopens in the Docker container environment, ready for development.
 ```

**Comment by TimothyXu** [comment]
Edited just now according to Professor's answer on Slack about what this task means.
