### ISSUE TITLE
Initial setup for simple page UI

### ISSUE THREAD

**Issue by kdokm** [2022-Spring-NYU-DevOps-Shopcarts/shopcarts#54]
**As a** eCommerce manager 
 **I need** a simple page UI  
 **So that** I can administer this application
   
 ### Details and Assumptions
 * Can copy professor's front end code and adjust to our service (in pet_steps.py)
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given our service is running
 When we go to the webpage for our service
 Then we have a graphical UI that can be used to perform all operations on our microservice
 ```

**Comment by TimothyXu** [comment]
Per Professor's comment in Slack, should we break this up into more pieces and implement each of the button/features as a separate story? In particular this will allow us to use the Acceptance Criteria for BDD via Behave

**Comment by kdokm** [comment]
I agree with @TimothyXu
