### ISSUE TITLE
Add Github Actions CI badge and Codecov

### ISSUE THREAD

**Issue by yjjw** [2022-Spring-NYU-DevOps-Shopcarts/shopcarts#62]
**As a** developer
 **I need** to add a Github Actions CI badge and Codecov badge to README.md
 **So that** everyone will know if the build is broken
   
 ### Details and Assumptions
 * Users can click the CI badge and see the build progress
 * Can click the codecov badge to see codecov report
 * Details on how to do this given in the lecture on CICD. Can copy the code from the example repo used in that lecture and just change the hyperlinks.

 ### Acceptance Criteria  
   
 ```gherkin
 Given we have set up the CI badge and codecov badge on our GitHub repo
 When our automatic CI tests fail with coverage 90%
 Then the CI badge should read failing and codecov badge should read 90%
 When our automatic CI tests pass with coverage 95%
 Then the CI badge should read passing and codecov badge should read 95%
 ```

**Comment by TimothyXu** [comment]
Added codecov badge in addition to GitHub CI Build badge
