### ISSUE TITLE
Delete Shopcarts

### ISSUE THREAD

**Issue by yjjw** [2022-Spring-NYU-DevOps-Shopcarts/shopcarts#9]
**As a** System Administrator
 **I need** to be able to delete shopcarts
 **So that** when users leave we don't have dead shopcarts in our database
   
 ### Details and Assumptions
 * DELETE method is used when creating the request
 * Expected status code 204 returned as response as well as an empty list
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given our service is running and there is a shopcart
 When we call DELETE on the relevant shopcart
 Then we get status code 204 and an empty list
 ```

**Comment by Adora2401** [comment]
I am not sure whether the role should be System Administrator, why not user?

**Comment by TimothyXu** [comment]
Answering for bookkeeping purposes: as discussed in the Backlog Refinement meeting on 22 Feb, it should be System Administrator because the user doesn't get any benefit from getting their shopping carts deleted; the sysadmin gets benefits from being able to delete shopping carts of inactive users.
