### ISSUE TITLE
UI of Create Shopcarts

### ISSUE THREAD

**Issue by TimothyXu** [2022-Spring-NYU-DevOps-Shopcarts/shopcarts#90]
**As a** System Administrator
 **I need** to have a GUI to create a new shopcart given a user_id
 **So that** I can easily start a new cart for a user without using CLI 
   
 ### Details and Assumptions
 * Add button "Create Shopcart", connect to create_shopcarts.
   
 ### Acceptance Criteria  
   
 ```gherkin
Given a set of items
  | user_id | item_id | item_name | quantity | price   |
  | 1001      | 1            |  ring1           |  2            |  1998  |
  | 1001      | 2            |  ring2          |  1             |  1.5     |
  | 1002     | 1            |  ring1           |  3             |  3        |
When we visit the "home page"
And we enter "1001" to the text box "User_ID"
And we press the button "Create-Shopcart"
Then we should see status code 400
And we should see message "User with id '1001' already has a non-empty shopcart."
When we enter "1001" to the text box "User_ID"
And we press the button "Retrieve"
Then we should see "ring1" in the results
And we should see "ring2" in the results

Given a set of items
  | user_id | item_id | item_name | quantity | price   |
  | 1001      | 1            |  ring1           |  2            |  1998  |
  | 1001      | 2            |  ring2          |  1             |  1.5     |
  | 1002     | 1            |  ring1           |  3             |  3        |
When we visit the "home page"
And we enter "1003" to the text box "User_ID"
And we press the button "Create-Shopcart"
Then we should see message "Successfully Added an empty Shopcart"
When we enter "1003" to the text box "User_ID"
And we press the button "Retrieve"
Then we should not see "ring1" in the results
And we should not see "ring2" in the results
 ```

**Comment by TimothyXu** [comment]
create_shopcarts has 3 possible uses (explained in README.md). I think only the first possible use is relevant for this GUI; the second use is the same as calling post on /shopcarts/<user-id>/items which will be handled by Add to Shop Cart button (create_items); the third use is an optional feature that would be difficult to do in GUI since we would need to change the GUI and add extra elements so I think we should just not implement it in GUI. Thoughts?

**Comment by kdokm** [comment]
I think the second use can also be implemented if we want, although it is kind of redundant... For the third use, I think it's fine to just leave it now. If there is need to have it in the GUI, we can add this feature later.

**Comment by TimothyXu** [comment]
Makes sense about the third use yes we can do that with commas. But about the second feature, I mean not only is it a redundant feature, I mean that if we implemented it, from the customers perspective it’ll behave in EXACTLY the same way as create_items (the user fills in all 5 text fields, then click add to shop cart). This surely will be exactly the same as how the user would use the second usage case of create_shopcarts? Doesn’t make sense to add another button if the feature is already done using button Add To Shop Cart

**Comment by kdokm** [comment]
@TimothyXu I think the only difference is that when the shopcart already has items, create shopcart with item will return error, and add to shopcart will simply add the item.
